version: '3'
services:

  mariadb:
    build:
      context: ./docker/services/mariadb
    environment:
      - TZ=${GENERAL_TIMEZONE}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    ports:
      - "${MARIADB_HOST_PORT}:3306"
    volumes:
      - ./docker/data/mariadb:/var/lib/mysql
      - ${MARIADB_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    restart: always

  phpmyadmin:
    build: ./docker/services/phpmyadmin
    environment:
      - TZ=${GENERAL_TIMEZONE}
      - PMA_HOST=mariadb
      - MYSQL_USER=${PHPMYADMIN_USER}
      - MYSQL_PASSWORD=${PHPMYADMIN_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${PHPMYADMIN_ROOT_PASSWORD}
    ports:
      - "${PHPMYADMIN_HOST_HTTP_PORT}:80"
    depends_on:
      - mariadb
    restart: always
